# Generated by Django 2.1.4 on 2019-02-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='evening',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='lunch',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='morning',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
